
const translations={en:{nav_home:"Home",nav_research:"Research",nav_projects:"Projects",nav_publications:"Publications",nav_updates:"Updates",nav_about:"About",nav_contact:"Contact",hero_eyebrow:"Forest ecologist & remote sensing researcher",hero_title_1:"Understanding forests",hero_title_2:"from field to space.",hero_text:"I study Mediterranean forest health and climate-driven ecosystem change by integrating Earth observation, field ecology, GIS and spatial modelling.",hero_cta_1:"Explore research",hero_cta_2:"View publications",current_focus:"Current focus",research_eyebrow:"Research",research_title:"Forest ecosystems under environmental change",research_lead:"My research combines ecological understanding with geospatial technologies to detect, quantify and explain changes in Mediterranean forests.",projects_eyebrow:"Projects & themes",projects_title:"Selected research directions",pub_eyebrow:"Publications",pub_title:"Scientific outputs",updates_title:"Latest research activity",updates_placeholder_title:"Professional updates",updates_placeholder_text:"This feed is ready for official LinkedIn API synchronization when access is available.",about_eyebrow:"About",about_title:"Ecology, Earth observation and maps.",about_text:"I am a forest ecologist and remote sensing researcher with a PhD in Agricultural Sciences. My work focuses on Mediterranean forest health, drought, climate change and geospatial analysis."},it:{nav_home:"Home",nav_research:"Ricerca",nav_projects:"Progetti",nav_publications:"Pubblicazioni",nav_updates:"Aggiornamenti",nav_about:"Profilo",nav_contact:"Contatti",hero_eyebrow:"Ecologo forestale & ricercatore in telerilevamento",hero_title_1:"Comprendere le foreste",hero_title_2:"dal campo allo spazio.",hero_text:"Studio la salute delle foreste mediterranee e le trasformazioni degli ecosistemi indotte dal clima integrando osservazioni della Terra, ecologia di campo, GIS e modellistica spaziale.",hero_cta_1:"Esplora la ricerca",hero_cta_2:"Vedi pubblicazioni",current_focus:"Temi attuali",research_eyebrow:"Ricerca",research_title:"Ecosistemi forestali nel cambiamento ambientale",research_lead:"La mia ricerca unisce interpretazione ecologica e tecnologie geospaziali per rilevare, quantificare e spiegare i cambiamenti nelle foreste mediterranee.",projects_eyebrow:"Progetti & temi",projects_title:"Linee di ricerca selezionate",pub_eyebrow:"Pubblicazioni",pub_title:"Produzione scientifica",updates_title:"Attività di ricerca recenti",updates_placeholder_title:"Aggiornamenti professionali",updates_placeholder_text:"Questa sezione è predisposta per la sincronizzazione con l'API ufficiale LinkedIn quando disponibile.",about_eyebrow:"Profilo",about_title:"Ecologia, osservazione della Terra e mappe.",about_text:"Sono un ecologo forestale e ricercatore in telerilevamento con un PhD in Scienze Agrarie. La mia attività si concentra sulla salute delle foreste mediterranee, siccità, cambiamento climatico e analisi geospaziale."}};
const nav=document.querySelector(".site-nav"),menu=document.querySelector(".menu-toggle"),theme=document.querySelector("#theme-toggle"),lang=document.querySelector("#lang-toggle");
menu?.addEventListener("click",()=>nav.classList.toggle("open"));
document.querySelectorAll(".site-nav a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")));
if(localStorage.getItem("theme")==="dark")document.body.classList.add("dark");
theme.textContent=document.body.classList.contains("dark")?"☾":"☼";
theme?.addEventListener("click",()=>{document.body.classList.toggle("dark");const d=document.body.classList.contains("dark");theme.textContent=d?"☾":"☼";localStorage.setItem("theme",d?"dark":"light")});
function setLanguage(l){document.documentElement.lang=l;document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(translations[l]?.[k])el.textContent=translations[l][k]});lang.textContent=l==="en"?"IT":"EN";localStorage.setItem("language",l)}
setLanguage(localStorage.getItem("language")||"en");lang?.addEventListener("click",()=>setLanguage(document.documentElement.lang==="en"?"it":"en"));
document.querySelector("#year").textContent=new Date().getFullYear();
let allPublications=[];
function renderPublications(){const q=(document.querySelector("#pub-search")?.value||"").toLowerCase(),y=document.querySelector("#pub-year")?.value||"";const list=allPublications.filter(p=>(!y||String(p.year)===y)&&(!q||[p.title,p.journal,...(p.authors||[])].join(" ").toLowerCase().includes(q)));document.querySelector("#publication-list").innerHTML=list.map(p=>`<article class="publication"><div class="pub-year">${p.year||""}</div><div><p class="pub-type">${[p.journal,p.volume,p.issue,p.pages].filter(Boolean).join(" · ")||p.type||"Publication"}</p><h3>${p.title||""}</h3><p class="pub-authors">${(p.authors||[]).join(", ")}</p></div><a class="pub-link" href="${p.doi?`https://doi.org/${p.doi}`:(p.url||"#")}" target="_blank" rel="noreferrer">↗</a></article>`).join("")||'<div class="loading-message">No publications found.</div>'}
async function loadPublications(){try{const r=await fetch("data/publications.json",{cache:"no-store"}),d=await r.json();allPublications=d.publications||[];document.querySelector("#last-sync").textContent=d.last_updated||"—";const sel=document.querySelector("#pub-year");[...new Set(allPublications.map(p=>p.year).filter(Boolean))].sort((a,b)=>b-a).forEach(y=>sel.insertAdjacentHTML("beforeend",`<option value="${y}">${y}</option>`));renderPublications()}catch(e){document.querySelector("#publication-list").innerHTML='<div class="loading-message">Publications temporarily unavailable. Please use ORCID.</div>'}}
document.querySelector("#pub-search")?.addEventListener("input",renderPublications);document.querySelector("#pub-year")?.addEventListener("change",renderPublications);loadPublications();
